#!/usr/bin/env sh

killall -q polybar

polybar_proc=$(pgrep -u $UID -x polybar)

for i in ${polybar_proc};do
  kill -9 $i
done

while pgrep -u $UID -x polybar >/dev/null;do sleep 1;done

MONITOR=LVDS1 polybar top &
MONITOR=LVDS1 polybar bottom &

echo "Polybar(s) launched..."
